### ISSUE TITLE
Navigation bar background

### ISSUE THREAD

**Issue by xmha97** [hashemi-hossein/ara-note#2]
Hi,
The navigation bar is light on dark mode!
![Screenshot_2023-03-09-22-16-12-793_ara.note.jpg](https://user-images.githubusercontent.com/23485114/224125123-4a3ef296-fcca-421d-86a1-e5a10ed414ee.jpg)
Please fix this issue.
Thanks 🙏

**Comment by hashemi-hossein** [comment]
fixed!

**Comment by xmha97** [comment]
Thanks 🙏
