### ISSUE TITLE
Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [hashemi-hossein/ara-note#3]
Hi, please support the Android 13 Themed App Icons feature.
![Screenshot_2023-03-09-22-16-34-170_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/224125333-a3a29f23-844a-4f00-9b7a-0f3686d36b86.jpg)
Thanks 🙏

**Comment by hashemi-hossein** [comment]
done!

**Comment by xmha97** [comment]
Thanks 🙏
