### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [hashemi-hossein/ara-note#4]
When I want to create a new note, the app crashes on my phone.

Android 13
Samsung S21 5G

**Comment by hashemi-hossein** [comment]
Thanks @mondlicht-und-sterne for your feedback
But I tested everything and I couldn't find the error and reproduce it
Could you tell me more about it?

**Comment by mondlicht-und-sterne** [comment]
Should I attach the "+" button as a picture ?

**Comment by hashemi-hossein** [comment]
Please uninstall and reinstall the app,
Then click on the plus button, type something and finally press back button (or click check mark icon on top-left if your phone language is left-to-right)
You should see what you typed in a card on home screen.

If the error which you said is still occur, please record your screen and send the video file here for clarification.

Thank you for your time.
